# How often do you want to log the training stats.
# network_list: 
#     gen: gen_optimizer
#     dis: dis_optimizer

distributed: False
image_to_tensorboard: True
snapshot_save_iter: 1000
snapshot_save_epoch: 20
snapshot_save_start_iter: 50
snapshot_save_start_epoch: 10
image_save_iter: 50
max_epoch: 200
logging_iter: 100
results_dir: ./eval_results

gen_optimizer:
    type: adam
    lr: 0.0001
    adam_beta1: 0.5
    adam_beta2: 0.999
    lr_policy:
        iteration_mode: True
        type: step
        step_size: 300000
        gamma: 0.2

trainer:
    type: trainers.face_to_face_trainer::Face2FaceTrainer
    pretrain_warp_iteration: 200000
    loss_weight:
      weight_perceptual_final: 4
    vgg_param_final:
      network: vgg19
      layers: ['relu_1_1', 'relu_2_1', 'relu_3_1', 'relu_4_1', 'relu_5_1']
      use_style_loss: True
      num_scales: 4      
      style_to_perceptual: 250
    init:
      type: 'normal'
      gain: 0.02
gen:
    type: generators.face_to_face_model::Face2FaceGenerator
    param:
      mapping_net:
        coeff_nc: 73
        descriptor_nc: 256
        layer: 3
      editing_net:
        layer: 3
        num_res_blocks: 2
        base_nc: 64
      common:
        image_nc: 3
        descriptor_nc: 256
        max_nc: 256
        use_spect: False
                

# Data options.
data:
    type: data.HDTF_dataset::HDTFDataset
    data_root: ./dataset/HDTF_face3dmmformer
    split: ./dataset/train_HDTF_face3dmmformer.txt
    statistics_file: ./dataset/HDTF_face3dmmformer_statistics.txt
    resolution: 256
    semantic_radius: 13
    train:
      batch_size: 10
      distributed: False
    val:
      batch_size: 8
      distributed: False

data_demo:
    type: data.HDTF_video_dataset::HDTFVideoDataset
    data_root: ./dataset/HDTF_face3dmmformer
    split: ./dataset/train_HDTF_face3dmmformer.txt
    statistics_file: ./dataset/HDTF_face3dmmformer_statistics.txt
    resolution: 256
    semantic_radius: 13
    train:
      batch_size: 10
      distributed: False
    val:
      batch_size: 8
      distributed: False

hdtf_data_demo:
  data_root: ./dataset/HDTF_face3dmmformer/train
  # video_name: WDA_JeanneShaheen0_000
  # video_name: WRA_KellyAyotte_000
  # video_name: WDA_ChrisVanHollen1_000
  # video_name: WDA_ChrisMurphy0_000
  video_name: WDA_KimSchrier_000
  # video_name: WDA_JeanneShaheen0_000
  # the deep3dface coeffcients directory path
  # pred_dir: /home/zhanghm/Research/Face/PIRender/WDA_JeanneShaheen0_000_condition_WDA_ChrisMurphy0_000
  pred_dir: /home/zhanghm/Research/V100/TalkingFaceFormer/test_dir/paper_PE_val_condition_WDA_KimSchrier_000_001_audio_WRA_KellyAyotte_000
